# Constants
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 720
IMAGE_WIDTH = 1024
IMAGE_HEIGHT = 1024
SCROLL_SPEED = 1.5
SCREEN_TITLE = "SpaceShootGame"
PLAYER_MOVEMENT_SPEED = 7
PLAYER_CHARACTER_SCALING = 2
PLASMA_RATE_OF_FIRE = 0.2
LAZER_RATE_OF_FIRE = 4
TILE_SCALING = 0.5
MUSIC_VOLUME = 30
MENU_BACKGROUND_IMAGE_FILE = ":resources:/images/space_shooter/Starfield_01-.png"
SETTINGS_BACKGROUND_IMAGE_FILE = ":resources:/images/space_shooter/Starfield_05.png"
LEVEL_MENU_BACKGROUND_IMAGE_FILE = ":resources:/images/space_shooter/Starfield_06.png"
LEVEL1_BACKGROUND_IMAGE_FILE = ":resources:/images/space_shooter/Blue_Nebula_08.png"
LEVEL2_BACKGROUND_IMAGE_FILE = ":resources:/images/space_shooter/Green_Nebula_07.png"
LEVEL3_BACKGROUND_IMAGE_FILE = ":resources:/images/space_shooter/Purple_Nebula_07.png"
PLAYER_BULLET_SPRITE = ":resources:\images\space_shooter\laserBlue01.png"
ENEMY_BULLET_SPRITE = ":resources:\images\space_shooter\laserRed01.png"
MAIN_MENU_MUSIC_FILE = ":resources:sounds/Ben Prunty - Space Cruise Title FTL_ Faster Than Light OST.mp3"
VICTORY_MENU_MUSIC_FILE = ":resources:sounds/Ben Prunty - Victory FTL_ Faster Than Light OST.mp3"
GAME_OVER_MUSIC_FILE = ":resources:sounds/Ben Prunty - BONUS Horror FTL_ Faster Than Light OST.mp3"
LEVEL1_MUSIC_FILE = ":resources:sounds/Ben Prunty - Colonial Battle FTL_ Faster Than Light OST.mp3"
LEVEL2_MUSIC_FILE = ":resources:sounds/Ben Prunty - Lanius Battle FTL_ Faster Than Light OST.mp3"
LEVEL3_MUSIC_FILE = ":resources:sounds/Ben Prunty - Hacking Malfunction Battle FTL_ Faster Than Light OST.mp3"
#DATA
ENEMY_BULLET_LIST = []